# Generated by Django 2.2 on 2021-02-02 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='staus_text',
            new_name='status_text',
        ),
    ]
